version: "3"

services:

  server:
    build: cur_arp_pkj/
    command: python ./app.py
    container_name: app_server
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mongo:4.4.3
    restart: unless-stopped
    container_name: data_base
    ports:
      - 5001:27017
