version: "3"

networks:
  app-network:
    driver: bridge
    name: "${DOCKER_NETWORK}"

volumes:
  dbdata:
    driver: local

services:
  server:
    build: .
    restart: unless-stopped
    container_name: app_server
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mongo:4.4.3
    restart: unless-stopped
    container_name: ${DOCKER_MONGO_CONTAINER}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - app-network
    volumes:
      - dbdata:/data/db
