version: "3"

networks:
  app-network:
    driver: bridge

services:
  server:
    build: .
    container_name: app_server
    ports:
      - 5000:5000
    networks:
      - app-network

    depends_on:
      - db

  db:
    image: mongo:4.4.3
    restart: unless-stopped
    container_name: data_base
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - /db_volume:/data/db
