GET http://127.0.0.1:5000/api/currencies/USD

###

POST http://127.0.0.1:5000/api/currencies
Content-Type: application/json

{
    "from": "USD",
    "to": "RUB",
    "value": 1
}

###

GET http://127.0.0.1:5000/res/5